version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: log/api.log
    when: MIDNIGHT
loggers:
  app.lsf:
    level: INFO
    handlers: [file_handler]
    propagate: False
root:
  level: INFO
  handlers: [file_handler]
