"""add group of storage  cluster id

Revision ID: a1d670c60836
Revises: d52a991af735
Create Date: 2026-04-02 09:21:01.923029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d670c60836'
down_revision: Union[str, Sequence[str], None] = 'd52a991af735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('storage_cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_groups_storage_cluster_id'), 'groups', ['storage_cluster_id'], unique=False)
    op.create_foreign_key(None, 'groups', 'storage_clusters', ['storage_cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_storage_cluster_id'), table_name='groups')
    op.drop_column('groups', 'storage_cluster_id')
    # ### end Alembic commands ###
