"""add storage usage

Revision ID: ac8fd17e3676
Revises: 
Create Date: 2026-04-01 11:09:04.043645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8fd17e3676'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregates', sa.Column('storage_cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_aggregates_storage_cluster_id'), 'aggregates', ['storage_cluster_id'], unique=False)
    op.create_foreign_key(None, 'aggregates', 'storage_clusters', ['storage_cluster_id'], ['id'])
    op.add_column('qtrees', sa.Column('storage_cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_qtrees_storage_cluster_id'), 'qtrees', ['storage_cluster_id'], unique=False)
    op.create_foreign_key(None, 'qtrees', 'storage_clusters', ['storage_cluster_id'], ['id'])
    op.add_column('storage_usages', sa.Column('storage_cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_storage_usages_storage_cluster_id'), 'storage_usages', ['storage_cluster_id'], unique=False)
    op.create_foreign_key(None, 'storage_usages', 'storage_clusters', ['storage_cluster_id'], ['id'])
    op.add_column('volumes', sa.Column('storage_cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_volumes_storage_cluster_id'), 'volumes', ['storage_cluster_id'], unique=False)
    op.create_foreign_key(None, 'volumes', 'storage_clusters', ['storage_cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volumes', type_='foreignkey')
    op.drop_index(op.f('ix_volumes_storage_cluster_id'), table_name='volumes')
    op.drop_column('volumes', 'storage_cluster_id')
    op.drop_constraint(None, 'storage_usages', type_='foreignkey')
    op.drop_index(op.f('ix_storage_usages_storage_cluster_id'), table_name='storage_usages')
    op.drop_column('storage_usages', 'storage_cluster_id')
    op.drop_constraint(None, 'qtrees', type_='foreignkey')
    op.drop_index(op.f('ix_qtrees_storage_cluster_id'), table_name='qtrees')
    op.drop_column('qtrees', 'storage_cluster_id')
    op.drop_constraint(None, 'aggregates', type_='foreignkey')
    op.drop_index(op.f('ix_aggregates_storage_cluster_id'), table_name='aggregates')
    op.drop_column('aggregates', 'storage_cluster_id')
    # ### end Alembic commands ###
