"""add storage usage info

Revision ID: ed3f354b8726
Revises: 29a301101543
Create Date: 2026-04-01 11:32:17.336336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3f354b8726'
down_revision: Union[str, Sequence[str], None] = '29a301101543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_clusters', sa.Column('storage_host', sa.String(length=512), nullable=True))
    op.add_column('storage_clusters', sa.Column('storage_port', sa.Integer(), nullable=True))
    op.add_column('storage_clusters', sa.Column('storage_user', sa.String(length=128), nullable=True))
    op.add_column('storage_clusters', sa.Column('storage_password', sa.String(length=128), nullable=True))
    op.drop_column('storage_clusters', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_clusters', sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('storage_clusters', 'storage_password')
    op.drop_column('storage_clusters', 'storage_user')
    op.drop_column('storage_clusters', 'storage_port')
    op.drop_column('storage_clusters', 'storage_host')
    # ### end Alembic commands ###
